FROM maven:3-openjdk-18 as build
WORKDIR /app
COPY . .
RUN mvn package -Dmaven.test.skip

FROM maven:3.8.1-openjdk-17-slim
COPY --from=build /app/target/*.jar /app/app.jar

# install python for worker mode
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.5 \
    python3-pip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080
CMD java -jar /app/app.jar 